name: Testing and TER deployment

on: [push, pull_request]

# If you do not rely on running other jobs besides the actual TER deployment, use this:
#on:
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  # Some basic test example
  tests:
    name: Run tests using PHP ${{ matrix.php-versions }} with TYPO3 ${{ matrix.typo3-versions }}

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        php-versions: [7.2]
        typo3-versions: [10.4]

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}-typo3-${{ matrix.typo3-versions }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}-typo3-${{ matrix.typo3-versions }}-composer-
            php-${{ matrix.php-versions }}-typo3-

      - name: Install composer dependencies
        run: composer require typo3/minimal "^${{ matrix.typo3-versions }}" --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: composer run-script test

  # The actual TER upload job
  tag-valid:
    name: Check if trigger is a valid tag

    # Run only if tests are successful
    needs: tests
    # Run only if it's a tag in general (as regex is not possible here)
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    # Save status for use in other jobs
    outputs:
      status: ${{ steps.check-tag.outputs.match }}

    steps:
      # Check for a valid tag, valid as in use your own regex if its a valid tag for your setup
      # By default, this will check for a "1.2.345" naming scheme
      - name: Check if trigger is a valid tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
          fi

  # The actual TER upload job
  ter-release:
    name: TER deployment running PHP ${{ matrix.php-versions }}

    # Depend on a valid tag
    needs: tag-valid
    if: needs.tag-valid.outputs.status == 'true'

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php-versions: [7.2]

    env:
      TYPO3_USER: ${{ secrets.TYPO3_USER }}

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}-composer-
            php-${{ matrix.php-versions }}-

      - name: Install composer dependencies
        run: COMPOSER_VENDOR_DIR=~/composer-vendor composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Upload to TER
        run: ~/composer-vendor/bin/upload ./ "$TYPO3_USER" "$TYPO3_PASSWORD" "${{ github.event.head_commit.message }}"
